# Generated by Django 5.2.4 on 2025-10-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalPuropse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='targetGroup',
        ),
        migrations.AlterField(
            model_name='homework',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to='uploads/homeworkRelated/'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
